### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [TermanEmil/NEAT-Driving-Car#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by TermanEmil** [comment]
It's under MIT license (I'll add it latter tonight).

The code is quite messy, so I'd suggest using OpenAi Gym https://gym.openai.com/envs/CarRacing-v0/
Or unity's api for AI https://unity.com/products/machine-learning-agents (I remember they had an agent for cars too)

If you still decide to go through this code, contact me through my email for any questions at all.

terman.emil@gmail.com

Just a side note: Genetics algorithms is not really the best for RL. QLearnings usually does better in most cases. Still Genetic Algorithms is much more intuitive. I started by implementing a Genetic algorithm for flappy birds.

Here are a few nice tutorials:
https://youtu.be/aeWmdojEJf0
https://youtu.be/8V2sX9BhAW8

**Comment by TermanEmil** [comment]
I've added a MIT License
